services:
    chibisafe:
        image: chibisafe/chibisafe:latest
        environment:
            - BASE_API_URL=http://chibisafe_server:8000
        expose:
            - 8001
        restart: unless-stopped

    chibisafe_server:
        image: chibisafe/chibisafe-server:latest
        volumes:
            - /var/lib/docker/volumes/chibisafe/database:/app/database:rw
            - /var/lib/docker/volumes/chibisafe/uploads:/app/uploads:rw
            - /var/lib/docker/volumes/chibisafe/logs:/app/logs:rw
        environment:
            - SERVE_UPLOADS_FROM=https://192.168.1.90:24424
        expose:
            - 8000
        restart: unless-stopped

    caddy:
        image: caddy:2-alpine
        volumes:
            - /var/lib/docker/volumes/Caddyfile:/etc/caddy/Caddyfile:ro
            - /var/lib/docker/volumes/uploads:/app/uploads:ro
        ports:
            - 24424:80
        environment:
            - BASE_URL=":80"
        restart: unless-stopped
